version: '3.1'

services:

  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: Reverse-Proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
        /volumes/nginx/certs:/etc/nginx/certs:ro
        /volumes/nginx/vhostd:/etc/nginx/vhost.d
        /volumes/nginx/config/settings.conf:/etc/nginx/conf.d/custom_settings.conf:ro

  portal:
    image: nginx
    container_name: Portal
    restart: always
    environment:
      - VIRTUAL_HOST=portal-jalmonaci.ddns.net
    volumes:
      - /storage/volumes/nginx/portal:/usr/share/nginx/html:ro
    
    factura:
    image: nginx
    container_name: Factura
    restart: always
    environment:
      - VIRTUAL_HOST=factura-jalmonaci.ddns.net
    volumes:
      - /storage/volumes/nginx/factura:/usr/share/nginx/html:ro

  erp:
    image: httpd
    container_name: ERP
    restart: always
    environment:
      - VIRTUAL_HOST=erp-jalmonaci.ddns.net
    volumes:
      - /storage/volumes/apache/erp:/usr/local/apache2/htdocs